name: Cypress Tests

on: [workflow_dispatch]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run E2E Tests Desktop
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e-desktop-ci
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: Cypress E2E Desktop

      - name: Publish Desktop Test results
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-desktop
          path: cucumber-report.html


      - name: Cypress run e2e Mobile
        uses: cypress-io/github-action@v6
        with:
          command: npm run e2e-mobile-ci
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: Cypress E2E Mobile

      - name: Publish mobile test results
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report-mobile
          path: cucumber-report.html
        
